### PR TITLE
Setup analysis modules

### PR DESCRIPTION
**Pull request by Kn99HN**

### CODE REVIEW

**Review by joyceluyy — APPROVED** [review]
Looks good to me. Will work on adding more scenario based on this.

**Comment by Kn99HN** [comment]
@joyceluyy Can you pull and test the first expectation1.txt file? For some reason, the checker is reporting false but I can't trace down why. The expectation is supposed to be true.

**Comment by Kn99HN** [comment]
I think this is a good stopping point for this PR as we achieve some basic analysis. Let's review this one before it becomes too big of a PR.

**Comment by joyceluyy** [comment]
Cool lets discuss it tomorrow. Thank you

**Pull request merged**
