### PR TITLE
Check fun

### LINKED ISSUE #5: Implement Checker
Checker should takes in an "expectation tree" created from #4 and a "trace tree" produced after reconciliation #2. 

While traverse the expectation tree, we will run the check function for each expectation statement. The possible-match result of each check function will form a search tree, with the height equals to the number of expectation statement ad width dependent on the number of variant statement. 

The Checker should carry out DFS on the search tree, to check if there exists a leaf node that reaches the end of the expectation tree and the trace tree at the same time.

### LINKED ISSUE #8: Create Check functions for each expectation statement
For each supported expectation statement, we will create a check function. The check function takes a tree node in the trace tree and return possible number of events it could match in the given subtree. 
- task
- send
- recv
- repeat
- maybe

### PR DESCRIPTION
**Pull request by joyceluyy**
- The check function takes in the expectation structure (%Validator.Recognizer) and the trace graph
- The check function deals with following expectation type 
--Validator.Recognizer
--Validator.Notice
--Validator.Send
--Validator.Receive
--Validator.repeat (repeat and maybe)

### CODE REVIEW

**Review by Kn99HN — CHANGES_REQUESTED** [review]
Looks good so far 🚀 Can we:
- add test cases for nested events/tasks?
- add spec to indicate the type and return value? I got confused about types of `detail` for instance?
- fix warning from reconciliation and checker files?
- Run formatter for the code.

**Comment by joyceluyy** [comment]
- Add the test case for nested task expectations
- Add spec for both checker and reconciliation functions
- Fixed the warning 
- Ran mix format'

Please let me know if there is anything need to be added or updated. Thank you

**Comment by joyceluyy** [comment]
Please let me know if there is anything need to be added or updated. Thank you

**Review by Kn99HN — APPROVED** [review]
LGTM 🚀

**Pull request merged**
